# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='kernel',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='系统内核'),
        ),
        migrations.AlterField(
            model_name='host',
            name='system',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='系统版本'),
        ),
    ]
