# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0002_auto_20170821_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_disk_histroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsik_num', models.FloatField(max_length=32, verbose_name='使用量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('host_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filing.Group', verbose_name='组的信息')),
            ],
        ),
    ]
