# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0003_group_disk_histroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_disk_histroy',
            old_name='dsik_num',
            new_name='disk_num',
        ),
    ]
