# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0004_auto_20170824_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_disk_histroy',
            old_name='host_ip',
            new_name='group_ip',
        ),
    ]
