# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0006_auto_20170824_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_disk_histroy',
            new_name='Group_disk_history',
        ),
    ]
