# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0007_auto_20170824_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='admin',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'user'), ('3', 'see')], default='2', max_length=32, verbose_name='状态'),
        ),
    ]
