# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0008_auto_20170828_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CQ_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='程序名称')),
                ('code_name', models.CharField(max_length=32, verbose_name='程序功能名称')),
                ('path', models.CharField(blank=True, max_length=32, null=True, verbose_name='程序路径')),
                ('start', models.CharField(blank=True, max_length=128, null=True, verbose_name='启动方法')),
                ('port', models.CharField(blank=True, max_length=128, null=True, verbose_name='端口号')),
                ('mapping', models.CharField(blank=True, max_length=128, null=True, verbose_name='外网映射')),
                ('www', models.CharField(blank=True, max_length=128, null=True, verbose_name='域名')),
                ('log', models.CharField(blank=True, max_length=128, null=True, verbose_name='日志路径')),
                ('note', models.TextField(blank=True, null=True, verbose_name='注释')),
            ],
            options={
                'verbose_name_plural': '车企程序信息',
            },
        ),
        migrations.CreateModel(
            name='CQ_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='业务线名称')),
                ('user', models.CharField(blank=True, max_length=32, null=True, verbose_name='总负责人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, max_length=32, null=True, verbose_name='qq')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('note', models.TextField(blank=True, null=True, verbose_name='登陆方式')),
                ('version', models.TextField(blank=True, null=True, verbose_name='各个服务版本信息')),
                ('to_code', models.ManyToManyField(blank=True, null=True, to='filing.Code', verbose_name='所属程序')),
            ],
            options={
                'verbose_name_plural': '车企信息',
            },
        ),
        migrations.CreateModel(
            name='CQ_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, unique=True, verbose_name='ip地址')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机名')),
                ('cpu_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='cpu数')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='cpu型号')),
                ('disk_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘个数')),
                ('disk_capacity', models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘总量')),
                ('disk_use', models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘已用')),
                ('mem', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存大小')),
                ('mem_use', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存已用')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌')),
                ('type', models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '交换机'), ('4', '路由器'), ('5', '防火墙'), ('6', 'VMware')], default='1', max_length=32, null=True, verbose_name='主机性质')),
                ('sn', models.CharField(blank=True, max_length=32, null=True, verbose_name='sn号')),
                ('system', models.CharField(blank=True, max_length=60, null=True, verbose_name='系统版本')),
                ('kernel', models.CharField(blank=True, max_length=60, null=True, verbose_name='系统内核')),
                ('status', models.CharField(choices=[('1', '在线'), ('2', '下线')], default='1', max_length=32, verbose_name='状态')),
                ('c_room', models.CharField(blank=True, max_length=32, null=True, verbose_name='机房')),
                ('position', models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜位置')),
                ('note', models.TextField(blank=True, max_length=256, null=True, verbose_name='注释')),
                ('to_code', models.ManyToManyField(blank=True, null=True, to='filing.Code', verbose_name='程序')),
                ('to_group', models.ManyToManyField(blank=True, null=True, to='filing.Group', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '车企主机信息',
            },
        ),
        migrations.AlterField(
            model_name='host',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '交换机'), ('4', '路由器'), ('5', '防火墙'), ('6', 'VMware')], default='1', max_length=32, null=True, verbose_name='主机性质'),
        ),
    ]
