# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0009_auto_20170906_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cq_code',
            options={'verbose_name_plural': '三方平台程序信息'},
        ),
        migrations.AlterModelOptions(
            name='cq_group',
            options={'verbose_name_plural': '三方平台项目信息'},
        ),
        migrations.AlterModelOptions(
            name='cq_host',
            options={'verbose_name_plural': '三方平台主机信息'},
        ),
    ]
