# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0010_auto_20170906_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cq_group',
            name='to_code',
            field=models.ManyToManyField(blank=True, null=True, to='filing.CQ_Code', verbose_name='所属程序'),
        ),
        migrations.AlterField(
            model_name='cq_host',
            name='to_code',
            field=models.ManyToManyField(blank=True, null=True, to='filing.CQ_Code', verbose_name='程序'),
        ),
        migrations.AlterField(
            model_name='cq_host',
            name='to_group',
            field=models.ManyToManyField(blank=True, null=True, to='filing.CQ_Group', verbose_name='所属项目'),
        ),
    ]
