# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0011_auto_20170906_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cq_group',
            name='www',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='平台访问地址'),
        ),
    ]
