# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0013_auto_20170906_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cq_group',
            name='version',
        ),
        migrations.AddField(
            model_name='cq_group',
            name='admin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='admin 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='cdh',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='cdh 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='duboo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='duboo 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='jdk',
            field=models.CharField(blank=True, default='jdk1.7.0_67', max_length=32, null=True, verbose_name='jdk 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='openservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='openservice 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='plat_gb_cli',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='plat_gb_cli 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='plat_gb_svr',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='plat_gb_svr 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='saveservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='saveservice 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='synservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='synservice 版本信息'),
        ),
        migrations.AddField(
            model_name='cq_group',
            name='term_gb_svr',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='term_gb_svr 版本信息'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='note',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='登陆方式'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='www',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='平台访问地址'),
        ),
    ]
