# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0014_auto_20170906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cq_host',
            name='ip',
            field=models.CharField(max_length=32, verbose_name='ip地址'),
        ),
    ]
