# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0016_auto_20170906_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cq_group',
            name='alarmservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='alarmservice 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='admin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='admin 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='cdh',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='cdh 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='duboo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='duboo 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='openservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='openservice 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='plat_gb_cli',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='plat_gb_cli 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='plat_gb_svr',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='plat_gb_svr 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='saveservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='saveservice 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='spark',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='spark 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='storm',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='storm 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='synservice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='synservice 版本'),
        ),
        migrations.AlterField(
            model_name='cq_group',
            name='term_gb_svr',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='term_gb_svr 版本'),
        ),
    ]
