# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0017_auto_20170906_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cq_group',
            name='jdk',
            field=models.CharField(blank=True, default='jdk1.7.0_67', max_length=32, null=True, verbose_name='jdk 版本'),
        ),
    ]
