# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0018_auto_20170906_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='salt_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='salt配置id'),
        ),
    ]
