# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0020_auto_20170914_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='all_ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='所有ip'),
        ),
    ]
