# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0021_host_all_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='salt配置id')),
                ('ip_info', models.CharField(blank=True, max_length=512, null=True, verbose_name='ip信息')),
            ],
        ),
    ]
