# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0022_host_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_net',
            name='ip_info',
            field=models.CharField(blank=True, max_length=3052, null=True, verbose_name='ip信息'),
        ),
    ]
