# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmname', models.CharField(max_length=32, verbose_name='项目名称')),
                ('start_time', models.CharField(max_length=32, verbose_name='开始时间')),
                ('end_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='结束时间')),
                ('text', models.CharField(blank=True, max_length=128, null=True, verbose_name='故障信息')),
            ],
            options={
                'verbose_name_plural': '所有平台故障信息',
            },
        ),
    ]
